name: "Feature Request ✨"
description: "Suggest a new feature or improvement for this project."
title: "Feature Request: [Enter a title]"
labels: ['enhancement']
body:
  - type: textarea
    id: summary
    attributes:
      label: "Feature Summary"
      description: "Provide a brief overview of the feature you're suggesting."
    validations:
      required: true
  - type: textarea
    id: problem-statement
    attributes:
      label: "What problem does this feature solve?"
      description: "Explain the problem you're facing that this feature will address."
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: "Describe the feature or change you'd like to see."
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: "Considered Alternatives"
      description: "Mention any alternative solutions or features you've thought about."
    validations:
      required: false
  - type: textarea
    id: extra-context
    attributes:
      label: "Additional Context"
      description: "Add any extra context or information related to the feature request."
    validations:
      required: false
  - type: checkboxes
    id: agreement
    attributes:
      label: "Code of Conduct Confirmation"
      description: "Please confirm the following:"
      options:
        - label: "I have searched for duplicate issues in the [issue tracker](https://github.com/NMFS-RADFish/boilerplate/issues)."
          required: true
        # - label: "I agree to follow this project's [Code of Conduct](https://example.com/code-of-conduct)."
        #   required: true

