name: Run tests

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install workspace dependencies
        run: npm install
        working-directory: .

      - name: Install main example build dependencies
        run: npm install
        working-directory: examples/main

      - name: Install main example test dependencies
        run: npm install --no-save @rollup/rollup-linux-x64-gnu
        working-directory: examples/main

      - name: Run main example tests
        run: npm test
        working-directory: examples/main

      - name: Run e2e tests
        run: npm run test:e2e
        working-directory: examples/main

  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install workspace dependencies
        run: npm install
        working-directory: .

      - name: Install dependencies
        run: npm install
        working-directory: examples/main

      - name: lighthouse mobile audit
        run: npm run lhci:mobile
        working-directory: examples/main
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: lighthouse desktop audit
        run: npm run lhci:desktop
        working-directory: examples/main
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
